services:
  loki:
    image: grafana/loki:${LOKI_VERSION}
    container_name: loki
    hostname: loki
    restart: unless-stopped

    networks:
      - backend
      - tools

    volumes:
      - ./loki/config/loki.yaml:/etc/loki/loki.yaml:ro
      - ./loki/runtime/volumes/data:/loki

    command:
      - -config.file=/etc/loki/loki.yaml
