services:
  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION}
    container_name: mailpit
    hostname: mailpit
    restart: unless-stopped

    ports:
      - "${MAILPIT_SMTP_PORT}:1025"

    networks:
      - backend

    volumes:
      - ./infra/mailpit/certificates:/certificates:ro
      - ./infra/mailpit/runtime/config:/config:ro
      - ./infra/mailpit/runtime/data:/data

    environment:
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_FILE: /config/smtp-auth.txt
      MP_SMTP_TLS_CERT: /certificates/mailpit.crt
      MP_SMTP_TLS_KEY: /certificates/mailpit.key
      MP_SMTP_REQUIRE_STARTTLS: "true"
      MP_UI_AUTH_FILE: /config/ui-auth.txt

