name: dev-platform

networks:

  frontend:
    name: ${FRONTEND_NETWORK}
    driver: bridge

  backend:
    name: ${BACKEND_NETWORK}
    external: true

  tools:
    name: ${TOOLS_NETWORK}
    driver: bridge

