services:
  caddy:
    image: caddy:${CADDY_VERSION}
    container_name: caddy
    hostname: caddy
    restart: unless-stopped

    ports:
      - "443:443"

    networks:
      - backend
      - tools

    volumes:
      - ./share/ca-certificates:/ca-certificates:ro
      - ./caddy/certificates:/certificates:ro
      - ./caddy/runtime/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/runtime/data:/data
      - ./caddy/runtime/config:/config
