# service        subdomain
caddy            *
postgresql       postgresql
kafka            kafka
redis            redis
jenkins          jenkins
mailpit          mailpit
grafana          grafana
loki             loki
prometheus       prometheus

