services:
  kafka:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka
    hostname: kafka
    restart: unless-stopped

    ports:
      - "${KAFKA_EXTERNAL_PORT}:29092"

    networks:
      - backend
      - tools

    volumes:
      - ./shared/ca-certificates:/ca-certificates:ro
      - ./infra/kafka/certificates:/certificates:ro
      - ./infra/kafka/runtime/config:/config:ro
      - ./infra/kafka/runtime/volumes:/var/lib/kafka/data

    command:
      - /opt/kafka/bin/kafka-server-start.sh
      - /config/server.properties

