# service        subdomain
caddy            *
postgresql       postgresql
kafka            kafka
redis            redis
minio            minio
mailpit          mailpit

jenkins          jenkins

grafana          grafana
loki             loki
prometheus       prometheus
