listen_addresses='*'

port=5432

ssl=on

ssl_cert_file='/certificates/postgresql.crt'
ssl_key_file='/certificates/postgresql.key'
ssl_ca_file='/certificates/ca.crt'

password_encryption=scram-sha-256

max_connections=100

shared_buffers=512MB

timezone='Asia/Kuala_Lumpur'

logging_collector=on
log_directory='log'
log_filename='postgresql-%Y-%m-%d.log'

log_connections=on
log_disconnections=on
